version: "3.7"

services:
    database:
        image: postgres
        container_name: gerenciar
        restart: always
        ports:
            - 5051:5432
        environment:
            - POSTGRES_USER=vinicius
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=gerenciar
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: manage
        restart: always
        ports: 
            - 3002:3002
        volumes: 
            - ./usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local