name: GerenciarTest
on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16      
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm run deploy

  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'gerenciar.dev.com'
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16      
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm run deploy

  deploy-hmg:
    runs-on: ubuntu-latest
    environment: 
      name: hmg
      url: 'gerenciar.dev.com'
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16      
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm run deploy


  deploy-prd:
    runs-on: ubuntu-latest
    environment: 
      name: prd
      url: 'gerenciar.dev.com'
    needs: deploy-hmg
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16      
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm run deploy
